VIA_ENABLE = yes
VIAL_ENABLE = yes
LT0_ENABLE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
SPACE_CADET_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = no

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

VIAL_ENCODERS_ENABLE = no

VIAL_INSECURE = yes
